require('ds18b20')
ds18b20.setup(4)
srv = net.createServer(net.TCP, 30)
srv:listen(80, function(conn)
    conn:on("receive", function(sck, payload)
        print(payload)
        sck:send("HTTP/1.0 200 OK\r\nContent-Type: text/plain\r\n\r\n" .. "Probe 1|" .. string.format("%.1f", ds18b20.readNumber(nil,'F')))
    end)
    conn:on("sent", function(sck) sck:close() end)
end)
